export enum FriendStatusEnum {
  BLOCKED = 'BLOCKED',
  REMOVED = 'REMOVED',
  FOLLOWING = 'FOLLOWING',
  FOLLOWED = 'FOLLOWED',
  PENDING = 'PENDING',
}

export enum FriendInteractionActionEnum {
  REQUEST = 'REQUEST',
  ACCEPT = 'ACCEPT',
  BLOCK = 'BLOCK',
  UNBLOCK = 'UNBLOCK',
  REMOVE = 'REMOVE',
  FOLLOW = 'FOLLOW',
  UN_FOLLOW = 'UN_FOLLOW',
  UN_FOLLOWED = 'UN_FOLLOWED',
}
