export enum VerifyTypeEnum {
  REGISTER = 'REGISTER',
  RECOVER_PASSWORD = 'RECOVER_PASSWORD',
  // CHANGE_EMAIL = 'CHANGE_EMAIL',
  // CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER',
  // ADD_EMAIL = 'ADD_EMAIL',
  // ADD_PHONE_NUMBER = 'ADD_PHONE_NUMBER',
}
